apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-retail
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: banking
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: Services/deployment/channel/retail
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}