apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: limits
spec:
  hosts:
  - "*"
  gateways:
  - banking
  http:
  - match:
    - uri:
        exact: /api/v1/limits
    route:
    - destination:
        host: helm-limits-ms-base
        port:
          number: 80                   