apiVersion: v2
name: transfers
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
- name: ms-base
  version: "1.0.0"
  repository: "file://../../common/ms-base"
